#!/bin/bash
set -e

# This script generates a detailed PR description for the Version Packages PR
# showing what type of version bump and which packages are being updated

# Check if there are any changesets
if [ ! -d ".changeset" ] || [ -z "$(ls -A .changeset/*.md 2>/dev/null | grep -v README)" ]; then
  echo "No changesets found."
  exit 0
fi

# Determine the highest version bump type
has_major=false
has_minor=false
has_patch=false

for file in .changeset/*.md; do
  if [ "$file" = ".changeset/README.md" ]; then
    continue
  fi
  
  if grep -q "^'@datum-cloud/datum-ui': major" "$file"; then
    has_major=true
  elif grep -q "^'@datum-cloud/datum-ui': minor" "$file"; then
    has_minor=true
  elif grep -q "^'@datum-cloud/datum-ui': patch" "$file"; then
    has_patch=true
  fi
done

# Determine bump type and description
if [ "$has_major" = true ]; then
  bump_type="major"
  bump_desc="This release contains **breaking changes**. Please review the changes carefully before merging."
elif [ "$has_minor" = true ]; then
  bump_type="minor"
  bump_desc="This release includes new features and improvements. Backward compatible with previous versions."
elif [ "$has_patch" = true ]; then
  bump_type="patch"
  bump_desc="This release contains bug fixes and minor improvements. Safe to merge."
else
  bump_type="unknown"
  bump_desc="Version bump detected."
fi

echo "## Release Type: \`$bump_type\`"
echo ""
echo "$bump_desc"
echo ""
echo "---"
echo ""
echo "## Changes"
echo ""

# Categorize changes
major_changes=()
minor_changes=()
patch_changes=()

for file in .changeset/*.md; do
  if [ "$file" = ".changeset/README.md" ]; then
    continue
  fi
  
  # Extract the bump type
  changeset_bump=$(grep "^'@datum-cloud/datum-ui':" "$file" | sed "s/'@datum-cloud\/datum-ui': //")
  
  # Extract the description (everything after the frontmatter)
  description=$(sed -n '/^---$/,/^---$/!p' "$file" | sed '/^---$/d' | sed '/^$/d' | sed "s/^'@datum-cloud\/datum-ui':.*//")
  
  case "$changeset_bump" in
    major)
      major_changes+=("$description")
      ;;
    minor)
      minor_changes+=("$description")
      ;;
    patch)
      patch_changes+=("$description")
      ;;
  esac
done

# Output categorized changes
if [ ${#major_changes[@]} -gt 0 ]; then
  echo "### Breaking Changes"
  echo ""
  for change in "${major_changes[@]}"; do
    echo "- $change"
  done
  echo ""
fi

if [ ${#minor_changes[@]} -gt 0 ]; then
  echo "### Features"
  echo ""
  for change in "${minor_changes[@]}"; do
    echo "- $change"
  done
  echo ""
fi

if [ ${#patch_changes[@]} -gt 0 ]; then
  echo "### Fixes"
  echo ""
  for change in "${patch_changes[@]}"; do
    echo "- $change"
  done
  echo ""
fi

echo "---"
echo ""
echo "## Release Process"
echo ""
echo "This PR updates package versions and changelogs based on merged changesets."
echo ""
echo "**When you merge this PR:**"
echo ""
echo "- Package will be published to npm"
echo "- GitHub Release will be created automatically"
echo "- Release notes will be generated from the changes above"
echo ""
echo "---"
echo ""
echo "_This PR was automatically generated by [changesets](https://github.com/changesets/changesets)._"
