version: '3'

env:
  ENV: config

dotenv: ['.env', '{{.ENV}}/.env']

includes:
  codegen: 
    taskfile: ./codegen/Taskfile.yaml
    dir: ./codegen

tasks:
  build:
    desc: build all apps and package
    cmd: bun run build

  install:
    desc: install the dependencies listed in package.json
    cmds:
      - bun install

  dev:
    desc: develop all apps
    cmds:
      - task: install
      - bun dev

  dev:docs:
    desc: develop docs
    cmds:
      - task: install
      - bun dev --filter={apps/docs}

  dev:operator:
    desc: develop docs
    cmds:
      - task: install
      - bun dev --filter={apps/operator}

  dev:storybook:
    desc: develop storybook
    cmds:
      - task: install
      - bun dev --filter={apps/storybook}

