version: '3'

tasks:
  codegen: 
    desc: run generate
    cmds:
      - task: generate
      - task: clean

  generate:
    desc: run generate
    cmd: npm run codegen

  clean: 
    # See https://github.com/dotansimha/graphql-code-generator-community/issues/501
    # TODO: find the right combination of deps to fix this
    desc: clean up badly generated code
    cmd: sed -i '' "s/'graphql-request\\/dist\\/types';/'graphql-request';/" src/schema.ts